name: Lint CSS with Stylelint and Reviewdog

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  checks: write
  pull-requests: write  # Needed for reviewdog

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier
        run: npx prettier --check "docs/**/*.{html,css,js}"

      - name: Run HTMLHint
        run: npx htmlhint "docs/**/*.html"

      - name: Run Stylelint with Reviewdog
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          stylelint_input: "docs/**/*.css"
          reporter: github-pr-review
          fail_on_error: true
      - name: Run Sytlelint CLI
        run: npx sytlelint "docs/*.css"      
